### ISSUE TITLE
BDSP_Reset Dialga/Palkia Battle detection in French version

### ISSUE THREAD

**Issue by BXL80** [brianuuu/AutoController_swsh#12]
When I execute the SmartProgram to reset Dialga/Palkia I have an issue with the battle detection due to my game language.

In French the button "Fight" in red is replace by "Attaque" that is way too big and takes a part in the square that is used to find only red colors.

Here is a picture : [https://ibb.co/mbWBPTt](url)
![https://ibb.co/mbWBPTt]

I didn't find what to modify to just push the detection square a bit to the right to make the program working, someone have an idear?

**Comment by brianuuu** [comment]
this is not cause by language, it's the capture card outputting more saturated video, read manual 1.5.7 for solution
