### ISSUE TITLE
Build Failed (V4.5.2)

### ISSUE THREAD

**Issue by jbarrymorejr** [brianuuu/AutoController_swsh#6]
Hello,

I am trying to setup and configure your Auto Controller Helper. However it consistently says the build has failed. Your Video tutorials are out of order. Can you point me to a video to help resolve this matter?

**Comment by brianuuu** [comment]
If should ask you to check the log, what does it say in there?

**Comment by jbarrymorejr** [comment]
make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4217b3)

**Comment by brianuuu** [comment]
https://www.avrfreaks.net/forum/make-interruptexception-caught-code-0xc00000fd-addr
it might have something to do with where you installed WinAVR

**Comment by jbarrymorejr** [comment]
Thank you. Solved. It was the space regarding install path for WinAVR.
